volumes:
  rabbitdata:
    driver: local
  rabbitlog:
    driver: local
  upload:
    driver: local
  working:
    driver: local
  sql:
    driver: local
  pgadmin:
    driver: local
  redis:
    driver: local
  redis-config:
    driver: local

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - AMate__FileProvider__Type=local
        - AMate__FileProvider__Path=/var/storage
    volumes:
        - "//c/Data/Files:/var/storage:rw"
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile

  rabbitmq:
    image: masstransit/rabbitmq:3.13.1
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitdata:/var/lib/rabbitmq/
        - rabbitlog:/var/log/rabbitmq

  ocrmypdf-server:
    image: sebfischer83/ocrmypdf-server:latest
    container_name: 'ocrmypdfserver'
    ports:
        - 10100:8080
    volumes:
      - upload:/var/upload
      - working:/var/working
  
  tesseract-server:
    image: hertzg/tesseract-server:latest
    container_name: "tesseractserver"
    ports:
      - 10101:8884
  
  gotenberg-server:
    image: gotenberg/gotenberg:8
    container_name: gotenbergserver
    ports:
      - 10102:3000

  db:
    image: postgres:16.1
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=lF18xggsdf4325d3z0mmN
    ports:
      - 5012:5432
    volumes:
      - sql:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "12500:80"
    restart: unless-stopped

  redis:
    image: redis/redis-stack:7.2.0-v8
    container_name: redis
    volumes:
       - redis:/data
       - redis-config:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
     - 6379:6379
     - 13333:8001