volumes:
  rabbitdata:
    driver: local
  rabbitlog:
    driver: local
  upload:
    driver: local
  working:
    driver: local
  sql:
    driver: local

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile

  rabbitmq:
    image: masstransit/rabbitmq:3.13.1
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitdata:/var/lib/rabbitmq/
        - rabbitlog:/var/log/rabbitmq

  ocrmypdf-server:
    image: sebfischer83/ocrmypdf-server:latest
    container_name: 'ocrmypdfserver'
    ports:
        - 10100:8080
    volumes:
      - upload:/var/upload
      - working:/var/working
  
  tesseract-server:
    image: hertzg/tesseract-server:latest
    container_name: "tesseractserver"
    ports:
      - 10101:8884
  
  gotenberg-server:
    image: gotenberg/gotenberg:8
    container_name: gotenbergserver
    ports:
      - 10102:3000

  db:
    image: postgres:16.1
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=lF18xggsdf4325d3z0mmN
    ports:
      - 5012:5432
    volumes:
      - sql:/var/lib/postgresql/data